spring:
  #MySQL配置
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://${host2}:3406/dajiuye?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: root
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# 微信小程序的appid和secret
wx:
  url: api.weixin.qq.com/sns/jscode2session
  appid: wxffd8f31f5bb7f05f
  secret: baa7959cdd43af09c9c5bcb0d3e426ea
  grant_type: authorization_code

# 发送微信http请求的
httppool:
  max_total: 200
  max_per_route: 100
  connect_timeout: 5000
  connection_request_timeout: 1000
  socket_timeout: 65000
  validate_after_inactivity: 2000

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
#  typeAliasesPackage: com.baomidou.springboot.entity
#  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
#    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
#    field-strategy: 2
    #驼峰下划线转换
#    db-column-underline: true
    #刷新mapper 调试神器
#    refresh-mapper: true
    #数据库大写下划线转换
#    capital-mode: false
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置
    #logic-delete-value: 0
    #logic-not-delete-value: 1
    #自定义填充策略接口实现
    #meta-object-handler: com.baomidou.springboot.xxx
    #自定义SQL注入器
    #sql-injector: com.baomidou.springboot.xxx
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志
logging:
  level:
    root: info
    com:
      lhf:
        dajiuye:
          mapper:
            debug
